### ISSUE TITLE
# Submit API verification key

### ISSUE THREAD

**Issue by cheerjohn** [6677-ai/tap4-ai-webui#11]
# Submit API verification key
SUBMIT_AUTH_KEY="xxxx"
这个Key从哪里拿？

**Comment by cheerjohn** [comment]
页面有出现过这个错误： Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3608636164

**Comment by tap4-ai** [comment]
SUBMIT_AUTH_KEY这个是作为你的自定义key，方便后续可以开放API支持自动化提交

**Comment by tap4-ai** [comment]
> 页面有出现过这个错误： Application error: a server-side exception has occurred (see the server logs for more information). Digest: 3608636164

https://mp.weixin.qq.com/s/VktoZ7f1Xo4ZmkXKJ5TOdQ
请根据这篇文章的介绍，检查下环境变量或者sql是否有执行

**Comment by cheerjohn** [comment]
解决了，谢谢
