### ISSUE TITLE
deployed to vercel: Status Ready yet  Application error:

### ISSUE THREAD

**Issue by CharlieLZ** [6677-ai/tap4-ai-webui#4]
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3581695166
![image](https://github.com/6677-ai/tap4-ai-webui/assets/48564262/10a588d1-43f5-489d-be08-df8faa55765d)

**Comment by CharlieLZ** [comment]
![image](https://github.com/6677-ai/tap4-ai-webui/assets/48564262/196d17af-e46a-432d-a98c-1789d2212e94)
Status
Ready
Created
9m ago by CharlieLZ

**Comment by tap4-ai** [comment]
> ![image](https://private-user-images.githubusercontent.com/48564262/336672458-196d17af-e46a-432d-a98c-1789d2212e94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NjM0NzYsIm5iZiI6MTcxODQ2MzE3NiwicGF0aCI6Ii80ODU2NDI2Mi8zMzY2NzI0NTgtMTk2ZDE3YWYtZTQ2YS00MzJkLWE5OGMtMTc4OWQyMjEyZTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE0NTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMjgxNTg5MDQ1YzIwMjY4YjM4Yzc3ZTQ3MDRkZWRlMGU0OTQ3ZDZjZTBmOGEwMjkwZDc1NDhhNDZhOTRkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s6U_pTWMunoGcCztR383ThVkxhXxcBqA-Yk3d7OhTRk) Status Ready Created 9m ago by CharlieLZ

请根据readme文档，更改里面的env环境变量，vercel的环境变量更改后，需要重新部署下
