### ISSUE TITLE
部署vercel后，在网站提交新网站，提示失败，而且看不到错误信息

### ISSUE THREAD

**Issue by qlxxkj** [6677-ai/tap4-ai-webui#5]
![image](https://github.com/6677-ai/tap4-ai-webui/assets/172968545/29771980-59c5-4dd7-b545-a4ae9a0c57bd)

**Comment by tap4-ai** [comment]
你好，supabase没有配置好，请看下你的supabase是否有执行项目的sql

**Comment by Firevvork** [comment]
> 你好，supabase没有配置好，请看下你的supabase是否有执行项目的sql

a

**Comment by qlxxkj** [comment]
确实是没有执行sql，已经搞定，感谢

**Comment by cheerjohn** [comment]
能分享下具体怎样执行sql，谢谢

**Comment by qlxxkj** [comment]
打开supabase数据库的sql editor面板，依次打开项目db/supabase目录下的sql文件，复制文件内所有sql语句到sql editor面板里面，执行sql。记住，每次只复制并执行一个文件里面的sql语句。
![image](https://github.com/user-attachments/assets/3040dd5d-b0d4-4558-b327-612c2c956f65)
